# Generated by Django 4.0.2 on 2022-02-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='categorie',
            field=models.CharField(choices=[('Epreuve', 'Epreuve'), ('Correction', 'Correction')], default='Epreuve', max_length=10),
        ),
    ]
