# Generated by Django 4.0.2 on 2022-02-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailMessage',
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
