# Generated by Django 4.0.2 on 2022-03-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_document_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nom',
            field=models.CharField(default='Doe', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='numero',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='prenom',
            field=models.CharField(default='John', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='sexe',
            field=models.CharField(default='H', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(upload_to='media'),
        ),
    ]
